#use bcp to load data into the tables in the Students Database
bcp Students.Performance.School in C:\school.txt -T -F 1 -q -c -t  ','
bcp Students.Performance.Sex in C:\sex.txt -T -F 1 -q -c -t  ','
bcp Students.Performance.AddressType in C:\address.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.FamSize in C:\famsize.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.Pstatus in C:\Pstatus.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.ParentEducation in C:\parentEdu.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.ParentJob in C:\parentJob.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.Reason in C:\reason.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.Guardian in C:\guardian.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.TravelTime in C:\travelTime.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.StudyTime in C:\studyTime.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.Failures in C:\failures.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.BadToExcellent in C:\BadToExcellent.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.LowtoHigh in C:\LowtoHigh.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.SmoteClass in C:\smoteClass.txt  -T -F 1 -q -c -t  ','
bcp Students.Performance.StudentMaster in C:\studentMaster.txt  -T -F 1 -q -c -t  ','
