#use bcp to load data into the tables in the Students Database
bcp Students.Performance.School in C:\school.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18  -F 2 -q -c -t  ','
bcp Students.Performance.Sex in C:\sex.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18  -F 2 -q -c -t  ','
bcp Students.Performance.AddressType in C:\address.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.FamSize in C:\famsize.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.Pstatus in C:\Pstatus.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.ParentEducation in C:\parentEdu.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.ParentJob in C:\parentJob.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.Reason in C:\reason.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.Guardian in C:\guardian.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.TravelTime in C:\travelTime.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.StudyTime in C:\studyTime.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.Failures in C:\failures.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.BadToExcellent in C:\BadToExcellent.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.LowtoHigh in C:\LowtoHigh.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.SmoteClass in C:\smoteClass.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 2 -q -c -t  ','
bcp Students.Performance.StudentMaster in C:\student-por_balanced.txt -S sqlcw18.database.windows.net -U SQLuser@sqlcw18.database.windows.net -P AzureTrial@18 -F 1 -q -c -t  ','
